### ISSUE TITLE
[REQUEST] Zigbee-Matter-Bridge add-on for Home Assistent (via HACS)?

### ISSUE THREAD

**Issue by Hedda** [antonio-gabriele/zigbee-matter-bridge#3]
Please consider making a Zigbee-Matter-Bridge add-on for Home Assistent (via HACS).

https://www.home-assistant.io/addons/

https://developers.home-assistant.io/docs/add-ons/tutorial/

https://addons.community/

At test if you want a lot more testers then offering an add-on via HACS (Home Assistant Community Store) would make it really easy for them to install and maintain updates for it.

https://hacs.xyz/

I also think that this could help Home Assistant’s Matter developers and testers too as this would signifigantly expand the numer of devices that could be tested in the Matter integration.

For reference it could be similar to the existing Zigbee2MQTT add-on.

https://www.zigbee2mqtt.io/guide/installation/03_ha_addon.html

https://github.com/zigbee2mqtt/hassio-zigbee2mqtt

**Comment by antonio-gabriele** [comment]
No Add-On is needed. Home Assistant will use Matter Bridge Device to inquire and control and monitor Zigbee Device. Indeed I'm testing Bridge using Home Assistant Companion. The porpuse of project is to implement zero-configuration Bridge.

**Comment by Hedda** [comment]
How could you run zigbee-matter-bridge in any better way if you have no other computer/appliance/device to run it on?

An add-on would be more user-friendly and is really needed for easy installation and update maintenence by non-advaned users of "Home Assistant Operating System", and needed to run natively on appliances like "Home Assistant Green" and "Home Assistant Yellow" which ships with "Home Assistant Operating System" preinstalled.

https://www.home-assistant.io/green

https://www.home-assistant.io/yellow

Today over 73% of all Home Assistant installations are running "Home Assistant Operating System"

https://analytics.home-assistant.io/

PS: "Home Assistant Operating System" (also known as "Home Assistant OS" and "HAOS", as well as formerly known as "HassOS" and "Hassio"), and to confuse things even more "Home Assistant Operating System" is today simply known as "Home Assistant" (while the actual Home Assistant application is today instead known as Home Assistant Core):

https://www.home-assistant.io/blog/2020/01/29/changing-the-home-assistant-brand/
